version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: proxy
    depends_on:
      - blue
      - green
  blue:
    image: jangajang/nmchu
    ports:
      - 8081:8081
    container_name: blue
    networks:
      - proxy_network
  green:
    image: jangajang/nmchu
    ports:
      - 8082:8082
    container_name: green
    networks:
      - proxy_network

networks:
  proxy_network: