server:
    port: 8081

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://158.180.93.233:3306/naengmechoo
        username: root
        password:

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true